# Details of the experiment for better trackability
experiment:
  name:  "Default"  #Name of the inference
  scene: "s0321_00"

# Parameters of the bounding box prediction 
pipeline:
  clustering:
    algo: "kmeans"  # Clustering algorithm, here kmeans
    k: 2            # Number of centroids
    init_centroids: "++"
  feature_extractor:
    network: "DINO"
    model: "vits8"

# Details of the data
data:
  name: ["ScanNet"]
  path: "data/scene0321_00"
  point_cloud_name: "scene0321_00_vh_clean_2.ply"
  point_cloud:
    path: "data/scene0321_00/scene0321_00_vh_clean_2.ply"  # path leading to point cloud
  images:
    path: "data/images"        # path leading to images

# Logs details
save:
  folder: "configs/logs/"        # logs folder
  point_cloud: True      # Flag
  images: True           # Flag


  